# actions
name: release

on:
  push:
    tags:
      - "*"

jobs:
  stage:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      upload: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  macos:
    needs: stage
    permissions: write-all
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release --package hexroll3-app
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.stage.outputs.upload }}
          asset_path: target/release/hexroll3-app
          asset_name: hexroll3-macos
          asset_content_type: application/octet-stream

  windows:
    needs: stage
    permissions: write-all
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release --package hexroll3-app
      - name: Zip assets
        run: |
          cd hexroll3-app
          7z a ../vvv.zip ../target/release/hexroll3-app.exe ./assets
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.stage.outputs.upload }}
          #asset_path: target/release/hexroll3-app.exe
          asset_path: vvv.zip
          asset_name: hexroll3-windows
          asset_content_type: application/octet-stream
