name: release

on:
  push:
    tags:
      - "*"
    # branches:
    #  - private

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  macos:
    permissions: write-all
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release --package hexroll3-app
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/hexroll3-app
          asset_name: hexroll3-macos
          asset_content_type: application/octet-stream
